#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

NODE_NAME=${NODE_NAME:-test}
iex --name $NODE_NAME@127.0.0.1 --cookie mycookie -S mix phx.server
