#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."
eval "$(mise env)"

script/bootstrap

docker compose up -d --wait

echo "==> Setting up project…"
# Ensure new env based config options are compiled
mix compile --force
mix setup

echo "==> The project is setup! 🚀 Is there demo data to load?"
